server:
  port: 8086
spring:
  application:
    name: feignservice
  cloud:
    nacos:
      server-addr: localhost:8848
    loadbalancer:
      ribbon:
        enabled: true
feign:
  hystrix:
    enabled: true
