server:
  port: 8086
spring:
  application:
    name: feignservice
  cloud:
    nacos:
      server-addr: localhost:8848
    loadbalancer:
      ribbon:
        enabled: true
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数
  sentinel:
    enabled: true
