server:
  port: 10010 # 网关端口
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://userservice
          predicates:
            - Path=/api/user/**
          filters:
            - AddRequestHeader=flag, flag
        - id: evaluation-service
          uri: lb://evaluationservice
          predicates:
            - Path=/api/evaluation/**
          filters:
            - AddRequestHeader=flag, flag
        - id: job-service
          uri: lb://jobservice
          predicates:
            - Path=/api/job/**
          filters:
            - AddRequestHeader=flag, flag
        - id: task-service
          uri: lb://taskservice
          predicates:
            - Path=/api/task/**
          filters:
            - AddRequestHeader=flag, flag
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期